name: Local Agent
version: 1.0.0
schema: v1
models:
  # 免费模型
  - name: Qwen2.5 Coder 7b Instruct
    provider: siliconflow
    model: Qwen/Qwen2.5-Coder-7B-Instruct
    apiKey: <apiKey>
    roles:
      - autocomplete
      - chat
      # - edit
    context:
      - provider: codebase
      - provider: web
    promptTemplates:
      autocomplete: |
        你是 {{{language}}} 编程专家，以下是代码补全上下文：
        `
        <|fim_prefix|>{{{prefix}}}<|fim_suffix|>{{{suffix}}}<|fim_middle|>
        `
  # 付费模型
  - name: Qwen3 Coder 30b Instruct
    provider: siliconflow
    model: Qwen/Qwen3-Coder-30B-A3B-Instruct
    apiKey: <apiKey>
    roles:
      - chat
    context:
      - provider: codebase
      - provider: web
prompts:
  - name: python-function-docs
    description: 生成 Python 函数注释
    prompt: |
      你是一名资深 Python 架构师，请为给定的代码生成详细的 Google 风格 Docstring 注释。
      要求：
      1. 格式严格遵循 Google Python Style Guide，包括：
        - 简短的功能概述（第一行）
        - Args: 参数说明（类型 + 含义）
        - Returns: 返回值说明（如有）
        - Raises: 可能抛出的异常（如有）
        - Todo: 代码可能需要改进的地方 (如有)
      2. 仅输出 ''' 中包裹的注释部分，不需要复制原有代码
      3. 保证注释如实反应给定的代码，如果需要修改在 Todo 部分写出

      例如给定代码：

      ```python
      def get_ema(y: np.ndarray, alpha: float = 0.9):
          if alpha < 0:
              raise ValueError("alpha 必须大于等于 0")

          y_ema = np.zeros(y.shape[0])
          y_ema[0] = y[0]
          
          for i in range(1, y.shape[0]):
              y_ema[i] = (1 - alpha) * y[i] + alpha * y_ema[i - 1]
          return y_ema
      ```

      有示例输出（不需要复制原有代码）：

      ```python
      def get_ema(y: np.ndarray, alpha: float = 0.9):
          '''
          计算指数移动平均值（EMA）。

          Args:
            y (np.ndarray): 输入的数组。
            alpha (float, optional): 平滑系数，默认为 0.9。必须大于等于 0。

          Returns:
            y_ema (np.ndarray): 计算得到的 EMA 数组。

          Raises:
            ValueError: 如果 alpha 小于 0。

          Todo:
            1. 缺少对 alpha 大于 1 情况的异常检查
          '''
      ```

      以下是给定的代码：

  - uses: roddsrod/document-python-function
